### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#167]
We don't need to have `bonitasoft.github.io` as we are not going to gh pages (#132).

### Tasks

- [x] rename the `bonitasoft.github.io` repository. There is no need to use this name which was only intended to be able to have the documentation site served with url without extra context. **decisions** --> `bonita-documentation-site`. Initial proposals were
  - bonita-doc-site: N/A, this is the name of the repository which build the documentation from the markdown sources
  - `bonita-site-generator`
  - `bonita-documentation-site`
  - `bonita-documentation-generator`
  - `bonita-doc-site-generator`
  - ...
- after the repo rename
  - [x] update the https://github.com/bonitasoft/bonita-documentation-theme readme to point to the new repo, see https://github.com/bonitasoft/bonita-documentation-theme/pull/43
  - update references to the `bonitasoft.github.io` repository (replace them by the new name)
    - [x] in the source code and documentation: see #197
    - [x] in opened issues
- update the github workflows (that triggers workflows in the doc site repository) in the documentation content repositories to reflect the repository name change.
  - Notice that GitHub handles redirection after the repository name change until a repository with the previous name is created.
  - Doing the workflow changes right now will prevent any side effects in the future if we decide to reuse the `bonitasoft.github.io` repository name later
  - [x] we should also rename the workflow that build and publish the documentation: it is currently named "generate documentation" whereas something like "Deploy to production" would be more accurate (at least, we publish an artifact site attached to the workflow). Rename both the file and the name values. See #218
  - [x] we should switch from `workflow_dispatch` to `repository_dispatch` (see https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event and https://github.com/peter-evans/repository-dispatch): the existing solution relies on the name of the wf, whereas the 2nd one on a custom event (like `source_documentation_change`) which reduce the adherence between the source and target repositories. See https://github.com/process-analytics/bpmn-visualization-examples/pull/147 for instance. See #198 
  - in addition, we should trigger workflow runs when files change in the `modules` folder and not only in `modules/ROOT`. This allows support for Antora modules.
  - repository updates
  	- [x] labs/bici, see https://github.com/bonitasoft/bonita-ici-doc/pull/131
  	- [x] cloud
  	- [x] bcd 3.4
  	- [x] bonita (7.9 to 2021.2)
