### ISSUE TITLE
Disable preview deploy attempt for non Bonitasoft contributor PR

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#239]
This applies to
- bonita-documentation-site
- bonita-documentation-theme
- document content repositories

This is really impacting for doc content repositories where most external contributions are done.

The concern comes from the way the GH actions behave in case of non Bonitasoft GH organization members and people without write permissions on the repository.
The preview is published to surge and a GH secrets is used to get the token for the publishing. In addition, a token is also needed to create a comment on the Pull Request. 

Actions run triggered by Pull Request by external contributors don't have access to the GH secrets, so the comments will never be created, the contributor won't see the preview url easily (it could check the GH actions logs, but this is painfull and require to know they exists) which defeats the purpose of the preview.
The lack of the token access make the GH actions run fail: the contributor has the impression that something is wrong in its contribution. See for instance https://github.com/bonitasoft/bonita-doc/pull/1476, https://github.com/bonitasoft/bonita-doc/pull/1483 or https://github.com/bonitasoft/bonita-doc/pull/1523

The preview is however created and a website made available because the [surge-preview action](https://github.com/afc163/surge-preview) we use has a flaw and use hard coded token in this case.
When the PR is closed or merged by a Bonitasoft member, the build in charge of cleaning the preview environment fails and a comment is added to the Pull Request about the preview environment removal failure. This is because in this case, the GH actions run has access to the secrets, so our regular surge token is used: as the domain of the preview is hold by another user, we cannot remove it and the domain removal fails.

See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ for more details about GH secrets access

### Tasks

- [x] bonita-documentation-site #361
- [x] bonita-documentation-theme #361
- document content repositories. Notice that implementing #270 will simplify the work to do
  - [x] bonita-doc (from 7.10, see https://github.com/bonitasoft/bonita-doc/pull/1747)
  - [x] bonita-labs. See https://github.com/bonitasoft/bonita-labs-doc/pull/136
  - [x] bonita-cloud https://github.com/bonitasoft/bonita-cloud-doc/commit/84d6f2eedaaf7ca2091a896e075cacac388c7ca5 and https://github.com/bonitasoft/bonita-cloud-doc/pull/32
  - [x] bonita-test-toolkit. See https://github.com/bonitasoft/bonita-test-toolkit-doc/commit/971944a9e270f9475fa12ec68816a10278536f42
- [x] Investigate how we can remove configuration duplication between workflows: #270
- [x] Extra: do not fail teardown if the preview environment doesn't exist #378

bonita-continuous-delivery: will be done with #418

**Comment by tbouffard** [comment]
Notice that we cannot use the surge-preview action with workflow_run for now, see https://github.com/afc163/surge-preview/issues/124
So the only way we have if we still want to use the surge-preview action, is to disable the preview deployment for non member of the repository as we did in https://github.com/process-analytics/bpmn-visualization-js/issues/1279.

**Comment by tbouffard** [comment]
All tasks are completed so closing.
