### ISSUE TITLE
Remove duplications in the GH workflows: surge preview in the documentation content repositories

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#270]
Currently, we duplicate the definition of the workflow across repositories and branches.
We have a preview script to limit the maintenance, but except configuration (component name), everything is duplicated.
For the push to production triggers, this is the same.

Idea: create a workflow/action in the documentation-site repository and use it in the documentation content repositories (targeting the master branch)

GitHub recently introduced "reusable workflows"
- https://github.blog/changelog/2021-10-05-github-actions-dry-your-github-actions-configuration-by-reusing-workflows/
- https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/
- https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

Others
- https://github.blog/changelog/2021-11-09-github-actions-conditional-execution-of-steps-in-actions/
- Composite actions may also helps https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

We could also develop a GitHub app (see #238) or develop specific GitHub actions.

### Resources

we currently do the checkout/clone of the doc-site repo using bash command
We could rely on the checkout action instead, see https://github.com/actions/checkout#checkout-multiple-repos-side-by-side to know how to it

### Tasks

Use the new action developed in #378. This will also fix #239.

- bonita-doc 
  - [x] initial https://github.com/bonitasoft/bonita-doc/pull/2071
  - [x] simplify current branch computation (via github context variable instead of using a bash script), see cloud. Started in https://github.com/bonitasoft/bonita-doc/pull/2118. To be propagated in next versions.
- [x] cloud https://github.com/bonitasoft/bonita-cloud-doc/commit/84d6f2eedaaf7ca2091a896e075cacac388c7ca5 and https://github.com/bonitasoft/bonita-cloud-doc/pull/32
- [x] labs https://github.com/bonitasoft/bonita-labs-doc/pull/136
- [x] test-toolkit https://github.com/bonitasoft/bonita-test-toolkit-doc/pull/26

bcd: will be done with #418

**Comment by tbouffard** [comment]
We decided to develop an dedicated action in the documentation-site repository that can be reused in documentation content.
The work is initiated with #378. It is under test on the bonita-doc content repository with https://github.com/bonitasoft/bonita-doc/pull/2071.

The actions developed here is in charge of:
- setup node
- checkout  the documentation repository
- build the preview with inputs provided 
- if the surge token is valid, deploy the preview on surge

It also manages the surge teardown on pull request close, which is only done if the surge domain exist and if the token is valid.
The checks done to verify the surge token, domain, ... will be done by a dedicated action (called by the action developed here). This dedicated action will be stored in the https://github.com/bonitasoft/actions repository.

**Comment by tbouffard** [comment]
The additional action is now available in the `bonitasoft/actions` repository: https://github.com/bonitasoft/actions/releases/tag/v1.2.0

**Comment by tbouffard** [comment]
All tasks are completed so closing.
