### ISSUE TITLE
Documentation content: migrate `attachment` links to the new Antora 3 syntax

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#360]
The oldest syntax is deprecated in Antora 3.0: https://docs.antora.org/antora/3.0/whats-new/#deprecation-summary. It used the `link:{attachmentsdir}` syntax.

Attachments are used in Bonita documentation at least starting from 7.10 (to be confirmed https://github.com/bonitasoft/bonita-doc/tree/7.9/modules/ROOT/attachments doesn't exist)
See https://github.com/bonitasoft/bonita-doc/commit/3cc5dabfb6728c3e34951694689974a9b2441b6b 
Even if 7.10 is out of support, we should migrate it if we want to be able to build this version (think about archive and  when we upgrade to an Antora version that doesn't support it anymore

They were also use in test-toolkit, but not anymore: https://github.com/bonitasoft/bonita-test-toolkit-doc/pull/5

Check the other repository: attachments live in a dedicated directory so it is easy to know if they are used. We shouldn't use cross component/version attachments so checking the directory existence in a branch is enough

**Tasks**

- [x] bonita 7.11+ https://github.com/bonitasoft/bonita-doc/pull/2059
- [x] bonita 7.10 https://github.com/bonitasoft/bonita-doc/pull/2061
- [x] review other repositories
  - ✔️ bcd (3.4-3.6)
  - ✔️ cloud
  - ✔️ labs
  - ✔️ test-toolkit (1.0)

**Comment by tbouffard** [comment]
All tasks are completed, so close the issue.
