### ISSUE TITLE
Doc-content repositories: configure the site start_page when building preview

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#385]
#372 added an option to configure the start_page when using the build preview script.
The workflow updates should be done as part of #270.

### Tasks

- [x] use the option in the bonita-cloud-doc repository
- [x] use the option in the bonita-test-toolkit repository
- [x] check if this is needed in the bonita-bonita-labs-doc repository. No, we only build a single branch
- [x] use the option in bonita-doc repository. This needs to be done in various branches and sometimes we are integrating several bonita versions in the preview, so this may need a way to automatically compute the version). Notice that we may introduce a way to avoid configuration duplication for this as part of #270 

For the bonita-continuous-delivery-doc repository, this will be done with #418
