### ISSUE TITLE
Content repositories: make usage of Pull Requests mandatory

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#398]
Today, people with write access in such repositories can directly push commits on documentation branches. We are configuring more and more tools and check in PR to improve content quality (preview environment, xref validation, ...)  and they are bypassed when push are done on documentation branches.
We have contact contributors and explain them why they should use PR (what are the benefits) but we still see bad behaviors.
This makes our efforts useless.

We (@tbouffard and @benjaminParisel ) proposed to make usage of Pull Requests mandatory.

Examples on the [bonita 2021.2 branch](https://github.com/bonitasoft/bonita-doc/commits/2021.2)
Probably done by mistake using the commit and file upload features on the GitHub web UI.

Jul 13, 2022 | Jul 27, 2022
---- | -----
![image](https://user-images.githubusercontent.com/27200110/184319501-175ef2cd-96b1-4df7-b0f9-677581b37d80.png) | ![image](https://user-images.githubusercontent.com/27200110/184319442-19b7cac4-e3be-4668-9723-a20dee868626.png)

### What we want to enforce

PR are mandatory to push to documentation content

**TODO** decide how many reviewers are mandatory. This should be repository specific and the 1st configuration should be explain here

We have running GH jobs that we can required to pass (Require status checks to pass before merging )
- Antora xref resolution
- PR metadata (title and description)
- Asciddoc content (no url to documentation-site, ...)

Include Administrators: yes except for specific scenarios (see below)

Require branches to be up to date before merging : **to decide!**

### Specific scenarios: Branch merges

**Note**: we use branch merges to port changes on old versions to new versions. A GH workflow run regularly to do it for the bonita-doc repository. Manually done elsewhere.

Automatically done for the bonita-doc repository, manual fix by developers when automatic merge fails.
The branch protection rules can be bypassed by administrators if configured (an action also exists to enable/disable this rules, see usage in https://github.com/process-analytics/bpmn-visualization-js/blob/v0.25.3/.github/workflows/release.yml for instance)
In that case, the GH account used for automation should have admin permissions for the related repositories.

Alternatively, we could use other options:
- "Allow specified actors to bypass required pull requests Specify people, teams, or apps who are allowed to bypass required pull requests."
- create a custom role to [bypass branch protections](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization#repository) https://github.blog/changelog/2022-08-18-bypass-branch-protections-with-a-new-permission/

In all cases, this also means that the merge cannot be done anymore by all accounts with write access on the repository. This adds content management tasks for people in charge of the documentation-site.

bcd

- manually done today
- make this automatic: #410 

test-toolkit

- Currently a single 1.0
- Manage it when they will have several branches as we do for bonita-doc?

### Tasks
- Configure quickly mandatory PR on repositories that have a single branches (no automatic merge, so no constraints)
  - [x] cloud. Done on 2022-10-07. 1 required reviewer, Require branches to be up to date before merging.
  - [x] labs. On 2022-08-12, PR are already mandatory (1 required reviewer), require status for 'cla assistant'. Require branches to be up to date before merging.
  - [x] test-toolkit. Done on 2022-10-07. 1 required reviewer, Require branches to be up to date before merging .
  - [x] bonita-doc
  - [x] bonita-doc archives branch. Requires 1 reviewer, no bypass (2022-10-05)
  - [x] bcd. Done on 2022-10-07. Same config as for bonita-doc to let develpers handle merge conflicts. See https://github.com/bonitasoft/bonita-documentation-site/issues/398#issuecomment-1256159299

**Comment by benjaminParisel** [comment]
On Bonita-doc only for now, we put the PR mandatory to add contribution in repository.
Some users (all members of bonitasoft/r&d group and bonita-ci), could bypass this rules. 
We need to do it to be able to propagate documentation between version (at least for conflict merge)

**Comment by tbouffard** [comment]
I have updated all repositories.
@benjaminParisel when you have time, can you review the configuration please?

For test-toolkit and cloud, the cla-assistant checks could be made mandatory, but it was not available in the settings page (no run since 7 days). We can add it later if we think this is valuable.
