### ISSUE TITLE
BCD doc: automatically propagate documentation upwards

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#410]
We initiated a workflow for bonita-doc in #292
After discussions with @uguy which is in charge of the BCD content, it appears this will also be usefull for BCD. Currently, merges are done manually, and only when someone has time time or remind to do it.

As we need to update the preview workflow in various branches of the bcd repositories (#239, #270, #326, ... ), this will also help.

### Tasks

- [x] manually merge 3.4 --> 3.5 --> 3.6 as this hasn't been done since december 2021. Done on 2022-09-02
- [x] adapt the script to be able to manage both bonita and bcd updates
- [x] update the GH workflow to run the script automatically
- [x] update the internal Bonitasoft documentation
