### ISSUE TITLE
BCD: apply workflows improvements already available in other repositories

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#418]
We are waiting for #410 prior being able to apply the improvements listed below. This can be done by using the shared action about surge-preview defined in the documentation-site repository
- #239
- #270
- #385
- #411

**Tasks**
- [x] 3.4: https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/195
- [x] 3.5. Merge from 3.4. Validated with https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/196/ and https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/198
- [x] 3.6. Merge from 3.5. Validated with https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/199 and https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/200

**Comment by tbouffard** [comment]
All tasks are completed. So closing this issue
