### ISSUE TITLE
Build: check if we can rebuild only a part of the site

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#46]
This may be useful if
- the whole generation is too long (fetch + generation)
- we want to limit changes committed to gh-pages

### Possible implementations
**TO BE DISCUSSED and probably tested**

#### Proposal 1

If possible, we could also only rebuild a single branch.

#### Proposal 2

Rebuild all
In the gh-pages branch, commit/push only the component version (folder including the version) which has changed + probably the related sitemap file
We could also detect the changed asciidoctor source file and only commit the related html file

### Tasks

Investigations
- [ ] do we really need it (performance, too much touched files)?
- [ ] poc what could be the best solution

Tasks if we want to do it
- [ ] check if Antora provide ways to do it
- [ ] provide new build scripts options for this site generation
- [ ] update the GH workflow (on worflow_dispatch) to only build the component passed as input (this requires #45)

**Comment by benjaminParisel** [comment]
Duplicate from #51

**Comment by tbouffard** [comment]
Reopened as I am closing #51 which is more related to gh-pages, and we have removed gh-pages.

**Comment by tbouffard** [comment]
It seems that we cannot only rebuild partially the documentation, see https://github.com/bonitasoft/bonitasoft.github.io/issues/51#issuecomment-785155979
