### ISSUE TITLE
Find a way to not be forced to store the Antora UI bundle in the repository

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#47]
Currently, after each changes and rebuild from the https://github.com/bonitasoft/bonita-documentation-theme we want to use in the documentation site, we have to store the new zip file in the repository.

Let's check if we can store it in a remote storage and retrieve it when generating the site.
See also https://docs.antora.org/antora/2.3/playbook/ui-bundle-url/

Potential targets
- assets of a GitHub release
- GitHub package
- ....

**Tasks**

- [x] Choose the solution: https://github.com/bonitasoft/bonita-documentation-site/issues/47#issuecomment-1096423104
- [x] Implement it: https://github.com/bonitasoft/bonita-documentation-theme/pull/107 and #366
- [x] Update the procedure about the theme release and update in the git repository (this is located in the README of the theme repository): https://github.com/bonitasoft/bonita-documentation-theme/pull/107
- [x] when the Antora configuration will use the bundle from the documentation-theme GitHub release, remove the former ui-bundle.zip file previously stored in the repository. This can be done in the 1st pull request that will use the GH release asset. See #369

**Comment by tbouffard** [comment]
All tasks are completed, issue closed
