### ISSUE TITLE
Add automatic tests for custom Antora extensions

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#546]
We have an extension to change the way the versions are sorted and we will have a new one to handle latest/next version alias used by the DocSearch client in the theme (#520 
Currently, we test the extensions "by hand" or by checking the preview running the "test sources content" #545

We could introduce unit tests to finely check the extension behavior.

### Tasks

- [ ] check the Antora documentation site and Zulip Chat for guidance about how to test Antora extensions
- [ ] choose a test framework
- [ ] decide if we keep "function" flavor or move to "class" flavor for the Antora Exension: it may be easier to test one form over the other
- [ ] Bonus: check if the extension can be written using ESM style instead of CommonJS
