### ISSUE TITLE
Convert build/publish preview actions to reusable workflow

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#700]
Currently, we use "composite actions, they produce hard to read logs and when used in documentation content repo, they are the sole step of the workflow.
When we created them, the concept of "reusable workflow" didn't exist, that's why we choose this "composite action"  implementation.
"Reusable workflow" are more convenient, so we could switch from action to reusable workflow.

Notice that in, the `build-pr-site` action that does the references validation, the `fail-on-warning` input default value should be `true` as we always want to fail on validation error. The current default is set to false, it was set to this value to be able to have a smooth transition in all repo during the introduction of Antora Atlas. The transition is now over, so we can change the default value.

https://github.com/bonitasoft/bonita-documentation-site/blob/ad588f0d009dfa126b069340209a6e6874ec1382/.github/actions/build-pr-site/action.yml#L17

The `build-pr-site` action could be replaced by a reusable workflow as well.

### Tasks

- [x] Introduce a reusable workflows to validate all references in replacements of the build-pr-site actions. the `fail-on-warning` input default value should be `true`. #714
- [x] Use the new reusable workflow in the documentation-site repository #714
- [x] Use the new reusable workflow in all content repositories, see #686
- [x] Remove the `build-pr-site` action once the new reusable workflow is used everywhere --> #760
- [x] Remove the `build-and-publish-pr-preview` action. Require #686 to be used in all content repositories --> #760
- [x] Remove the `upload-pr-built-site-artifact` action. Require #686 and the new reusable workflow to be used in all content repositories --> #760
