### ISSUE TITLE
Make the production build fails when Antora generates warnings

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#776]
As mentioned in #237
> The reference validation is done on all Pull Requests for a while. So, new errors should not be introduced.
Notice that if reference errors are found, this doesn't prevent the PR from being merge. So, theoretically, nothing prevents from introducing errors in production but this never happened in the past.

However, it doesn't prevent errors from occurring when porting changes from a version to a new one. This recently happened (see https://github.com/bonitasoft/bonita-doc/pull/2825 for the whole investigation and fix) and broken references (due to missing AsciiDoc attribute) were introduced in production.

In the past, we have only set the production build to fail when Antora generates errors.
There were some old/out-of-support documentation content branches that generated warnings. As they are no longer updated, they prevented to enable "fail on warnings".
Such branches may not exist, and if so, there could be a few warnings to fix.

### Tasks

- [x] Review production build logs to identify the repository and branches that generate warnings. See files below
- [x] Fix warnings in Bonita 7.11 https://github.com/bonitasoft/bonita-doc/commit/a9041b952dd752d95ec5923fac71d23347be32d8
- [x] Fix warnings in Bonita 2021.1 https://github.com/bonitasoft/bonita-doc/commit/165ae6ca1644c769f06bb5c064eeba08c128c0a0
- [x] Fix warnings in Bonita 2022.1 https://github.com/bonitasoft/bonita-doc/commit/857d0b45de41bb55aa98cd6427ac729d2034befa
- [x] Validate that all warnings have been fixed (check production logs) - production build [logs_20240828-092514_27693696828.zip](https://github.com/user-attachments/files/16781475/logs_20240828-092514_27693696828.zip)
- [x] Enable "fail on warnings" in the production build #777

Initial production Logs and warnings detection
- [logs_20240828-061551_27686541707.zip](https://github.com/user-attachments/files/16780747/logs_20240828-061551_27686541707.zip)
- [detections_with_build_20240828-061551.txt](https://github.com/user-attachments/files/16780750/detections_with_build_20240828-061551.txt)
